import "./globals.css";

export const metadata = {
	title: "Quora - A place to share knowledge and better understand the world",
	// description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
