import NextThemeProvider from "@/components/contexts/theme-provider";
import "./globals.css";
import { getServerSession } from "next-auth";

export const metadata = {
	title: "Quora - A place to share knowledge and better understand the world",
	// description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	// const session = await getServerSession();
	// console.log(session);

	return (
		<html lang="en">
			<body>
				<NextThemeProvider>
					{children}
					<div id="portal"></div>
				</NextThemeProvider>
			</body>
		</html>
	);
}
